# linux matrix
language: python
os: linux
python:
    - "3.6"
    - "3.5"
    - "3.4"
    - "2.7"
env:
  - MPI=
  - MPI=1

# OSX matrix
matrix:
    include:
        - os: osx
          osx_image: xcode10.1
          language: generic
          env: PYTHON_VERSION=python2 MPI=
        - os: osx
          osx_image: xcode10.1
          language: generic
          env: PYTHON_VERSION=python3 MPI=


# System packages
addons:
    apt:
        packages:
            - gfortran
            - libblas3
            - liblapack3
            - openmpi-bin
            - libopenmpi-dev
    homebrew:
        packages: 
            - gcc
            - python2
            - python3

before_install:
    - pip install flake8
    - flake8 .

    # OSX setup
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
      then 
          brew link gcc;
          pip install virtualenv;
          virtualenv venv -p $PYTHON_VERSION;
          source venv/bin/activate;
          if [[ "$PYTHON_VERSION" == "python3" ]];
          then 
               pip install --upgrade "https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl";
          else
               pip install --upgrade "https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py2-none-any.whl";
          fi;
      fi

    # PolyChord install
    - pip install numpy
    - git clone https://github.com/PolyChord/PolyChordLite PolyChord
    - cd PolyChord
    - make MPI=$MPI pypolychord
    - if [ "$MPI" ]; then 
          CC=mpicc CXX=mpicxx python setup.py install;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
          CC=gcc-8 CXX=g++-8 python setup.py install;
      else 
          python setup.py install;
      fi
    - cd ..

    # MultiNest install
    - git clone https://github.com/farhanferoz/MultiNest MultiNest_repo
    - cp -r MultiNest_repo/MultiNest_v3.11_CMake/multinest MultiNest
    - mkdir -p MultiNest/build
    - cd MultiNest/build
    - cmake ..
    - if [ "$MPI" ]; then 
          make multinest_mpi_shared;
      else
          make multinest_shared;
      fi;
    - cd ../../
    - export LD_LIBRARY_PATH=$PWD/MultiNest/lib/:${LD_LIBRARY_PATH} 

    # PyMultiNest install
    - git clone https://github.com/JohannesBuchner/PyMultiNest PyMultiNest
    - cd PyMultiNest
    - python setup.py install
    - cd ..
    - mkdir chains


install:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov codecov
    - if [ "$MPI" ]; then pip install mpi4py; fi


# Run tests
script:
    - if [ "$MPI" ];
      then mpirun -np 2 python -m pytest tests;
      else python -m pytest tests --cov=pybambi;
      fi

# Run coverage summary
after_success:
    - codecov
